== Deployment

When development is done, unit tested and reviewed, the next step is to deploy the changes to production.
This is done via the classic Change and Transport System (CTS).

=== Deployment Process Overview

Most steps of the deployment process are automated. A failure at a late stage indicates a need for earlier process improvements to detect such issues.

image::img/deployment.drawio.svg[align="center"]

=== System SCI checks

Static analysis feedback is provided to the developer immediately on the first push.

In GitHub, the code is isolated from the system's structure. SAP Code Inspector (SCI) can be used to perform additional checks, especially for assessing aspects like package structure, which GitHub alone does not handle.

=== Sequencing

Development projects often have dependencies that may not yet be available in the production environment. This can cause issues when moving the transport to production.

This can be discovered already in the pull request during development, eg. via the abaplint.app cross check or parallel changes feature.

To help checking the SAP standard transaction `/SDF/TRCHECK` can be used.

And for final verification, the transport is imported into the `STG` system, just previously to importing into the `PRD` system.

// todo, Heliconia Labs will provide more tooling in this area in the future

=== Rollback

Transports can be rolled back by creating an additional transport with the original contents.

// todo, implement rollback feature

// todo, BAdI `CTS_REQUEST_CHECK`, `CHECK_BEFORE_RELEASE`

// todo, reconciliation ?

// todo, irreversible changes, eg. DDIC => abaplint.app feature / warning
